### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by LabuserTu** [thladnik/vxPy-app#1]
ERROR   15:27:56,159 vxpy...ces.camera.basler_pylon Unable to grab frame from <vxpy.devices.camera.basler_pylon.BaslerCamera object at 0x7f93648b5070> // 3791651083, The image stream is out of sync.

Camera can crash during recording. Problem detecting camera. Can be fixed by unplugging and replugging camera USB.

**Comment by thladnik** [comment]
Found to be most likely due to bad USB connection.
